name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Every sunday at midnight
    - cron:  '0 0 * * 0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm run lint

  integration:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        eslint: ["4.7", latest, next]
        include:
          # Windows support
          - os: windows-latest
            eslint: latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: bash tools/integration-tests.bash ${{ matrix.eslint }}

  test:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16, 17]
        eslint: [latest]
        include:
          # Node 10 support: will be dropped in next major version
          - os: ubuntu-latest
            node: 10
            eslint: 7

          # ESLint 4.7 support: lowest version supported
          - os: ubuntu-latest
            node: 16
            eslint: "4.7"

          # Upcoming ESLint major version support
          - os: ubuntu-latest
            node: 16
            eslint: next

          # Windows support
          - os: windows-latest
            node: 16
            eslint: latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm install eslint@${{ matrix.eslint }}
      - run: npm test
