name: Tests

on:
  pull_request:
  push:
  schedule:
    # Every sunday at midnight
    - cron:  '0 0 * * 0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - run: npm run lint

  integration:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        eslint:
          - "4.7"
          - 7
          - 8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - run: ESLINT_VERSION=${{ matrix.eslint }} ./tools/integration-tests.bash

  test:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 16
          - 17
        eslint:
          - 7
          - 8
        include:
          - node: 10
            eslint: 7
            os: ubuntu-latest
          - node: 12
            eslint: 7
            os: ubuntu-latest
          - node: 12
            eslint: 8
            os: ubuntu-latest
          - node: 14
            eslint: 7
            os: ubuntu-latest
          - node: 14
            eslint: 8
            os: ubuntu-latest
          - node: 16
            eslint: "4.7"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm install eslint@${{ matrix.eslint }}
      - run: npm test
